# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: logging.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'logging.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rlogging.proto\"\'\n\nLogRequest\x12\x0c\n\x04uuid\x18\x01 \x01(\t\x12\x0b\n\x03msg\x18\x02 \x01(\t\"\x1d\n\x0bLogResponse\x12\x0e\n\x06status\x18\x01 \x01(\t\" \n\x0cLogsResponse\x12\x10\n\x08\x61ll_msgs\x18\x01 \x01(\t\"\x07\n\x05\x45mpty2[\n\x0eLoggingService\x12\'\n\nLogMessage\x12\x0b.LogRequest\x1a\x0c.LogResponse\x12 \n\x07GetLogs\x12\x06.Empty\x1a\r.LogsResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'logging_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_LOGREQUEST']._serialized_start=17
  _globals['_LOGREQUEST']._serialized_end=56
  _globals['_LOGRESPONSE']._serialized_start=58
  _globals['_LOGRESPONSE']._serialized_end=87
  _globals['_LOGSRESPONSE']._serialized_start=89
  _globals['_LOGSRESPONSE']._serialized_end=121
  _globals['_EMPTY']._serialized_start=123
  _globals['_EMPTY']._serialized_end=130
  _globals['_LOGGINGSERVICE']._serialized_start=132
  _globals['_LOGGINGSERVICE']._serialized_end=223
# @@protoc_insertion_point(module_scope)
